export const RP_NAME = Deno.env.get('RP_NAME') || 'Solis'
export const RP_ID = Deno.env.get('RP_ID') ||'localhost'
export const RP_ORIGIN = Deno.env.get('RP_ORIGIN') || 'http://localhost:8000'
export const DOMAIN = Deno.env.get('DOMAIN') || 'localhost'
export const KV_PATH = Deno.env.get('KV_PATH') || './data/kv.db'